trigger:
  branches:
    include:
      - main  # Adjust based on your main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # This checks out your code from GitHub

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - script: |
      terraform init
      terraform plan
      terraform apply tfplan
    displayName: 'Run Terraform'
    