
trigger:
  branches:
    include:
      - main  # Adjust based on your main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - script: |
      terraform init
      terraform plan
      terraform apply -auto-approve
       terraform init -reconfigure -backend-config="resource_group_name=rg-first-aj-02" -backend-config="storage_account_name=storageaccountlmslms" -backend-config="container_name=tfstate"
    displayName: 'Run Terraform'
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)